#!/usr/bin/env python3
"""Generate C++ entity table from HTML5 entities.json."""

import json
import urllib.request
import sys

def main():
    url = "https://html.spec.whatwg.org/entities.json"
    try:
        with urllib.request.urlopen(url) as resp:
            data = json.loads(resp.read())
    except Exception as e:
        print(f"Error fetching entities: {e}", file=sys.stderr)
        sys.exit(1)

    entries = {}
    for name, info in data.items():
        if name.endswith(';'):
            key = name[1:-1]
            cps = info['codepoints']
            entries[key] = cps

    sorted_entries = sorted(entries.items())

    print("// AUTO-GENERATED by scripts/gen_entities.py — do not edit")
    print("// HTML5 named character references")
    print("// Include this file inside an anonymous namespace that has")
    print("// encode_utf8() available.")
    print()
    print("struct EntityEntry {")
    print("  const char *name;")
    print("  uint32_t codepoints[2];")
    print("};")
    print()
    print(f"static const EntityEntry entity_table[] = {{")
    for name, cps in sorted_entries:
        if len(cps) == 1:
            print(f'  {{"{name}", {{{hex(cps[0])}, 0}}}},')
        else:
            print(f'  {{"{name}", {{{hex(cps[0])}, {hex(cps[1])}}}}},')
    print("};")
    print()
    print(f"static const size_t entity_table_size = {len(sorted_entries)};")
    print()
    print("std::optional<std::string> lookup_entity(std::string_view name) {")
    print("  size_t lo = 0, hi = entity_table_size;")
    print("  while (lo < hi) {")
    print("    size_t mid = lo + (hi - lo) / 2;")
    print("    int cmp = name.compare(entity_table[mid].name);")
    print("    if (cmp == 0) {")
    print("      std::string result;")
    print("      result += encode_utf8(entity_table[mid].codepoints[0]);")
    print("      if (entity_table[mid].codepoints[1] != 0) {")
    print("        result += encode_utf8(entity_table[mid].codepoints[1]);")
    print("      }")
    print("      return result;")
    print("    } else if (cmp < 0) {")
    print("      hi = mid;")
    print("    } else {")
    print("      lo = mid + 1;")
    print("    }")
    print("  }")
    print("  return std::nullopt;")
    print("}")

if __name__ == "__main__":
    main()
